### ISSUE TITLE
jquery/rails/railtie.rb:9:in `block in <class:Railtie>': undefined method `join' for nil:NilClass

### ISSUE THREAD

**Issue by shlima** [sstephenson/ruby-ejs#17]
Hello, unfortunately I catch the error with Rails 4.1 and els 1.1.1 while blotting my application:
(ejs 1.0.0 works fine)

```
/Users/alex/.rvm/gems/ruby-2.1.1/gems/jquery-rails-2.1.4/lib/jquery/rails/railtie.rb:9:in `block in <class:Railtie>': undefined method `join' for nil:NilClass (NoMethodError)
    from /Users/alex/.rvm/gems/ruby-2.1.1/gems/activesupport-4.1.0.rc2/lib/active_support/lazy_load_hooks.rb:36:in `call'
    from /Users/alex/.rvm/gems/ruby-2.1.1/gems/activesupport-4.1.0.rc2/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
    from /Users/alex/.rvm/gems/ruby-2.1.1/gems/activesupport-4.1.0.rc2/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
    from /Users/alex/.rvm/gems/ruby-2.1.1/gems/activesupport-4.1.0.rc2/lib/active_support/lazy_load_hooks.rb:44:in `each'
    from /Users/alex/.rvm/gems/ruby-2.1.1/gems/activesupport-4.1.0.rc2/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
    from /Users/alex/.rvm/gems/ruby-2.1.1/gems/railties-4.1.0.rc2/lib/rails/application.rb:121:in `initialize'
    from /Users/alex/.rvm/gems/ruby-2.1.1/gems/railties-4.1.0.rc2/lib/rails/railtie.rb:171:in `new'
    from /Users/alex/.rvm/gems/ruby-2.1.1/gems/railties-4.1.0.rc2/lib/rails/railtie.rb:171:in `instance'
    from /Users/alex/.rvm/gems/ruby-2.1.1/gems/railties-4.1.0.rc2/lib/rails/application.rb:90:in `inherited'
```

**Comment by Byronlee** [comment]
The problem has been solved?I met the same problem
